services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      DB_HOST: db-test
      DB_PASS: root
    volumes:
      - ./tests:/app/tests

  db-test:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress_test
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 2s
      timeout: 5s
      retries: 10
