name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: code-checkout

      - name: Validate composer.json and composer.lock
        id: composer-validate
        run: composer validate

      - name: Install dependencies
        id: install-dependencies
        run: make composer

      - name: PHPCS checker
        id: php-codesniffer
        run: make lint
